<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PizzaAddonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pizza_addons = [
            
            //fifth pizza //small
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Cheese',
                'value' => 0.90,
                'description' => 'Cheese',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Tomato sauce',
                'value' => 0.90,
                'description' => 'Tomato sauce',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Pepperoni',
                'value' => 0.90,
                'description' => 'Pepperoni',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Ham',
                'value' => 0.90,
                'description' => 'Ham',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Chicken',
                'value' => 0.90,
                'description' => 'Chicken',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Minced beef',
                'value' => 0.90,
                'description' => 'Minced beef',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Onions',
                'value' => 0.90,
                'description' => 'Onions',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Green peppers',
                'value' => 0.90,
                'description' => 'Green peppers',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Mushrooms',
                'value' => 0.90,
                'description' => 'Mushrooms',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Sweetcorn',
                'value' => 0.90,
                'description' => 'Sweetcorn',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Jalapeno peppers',
                'value' => 0.90,
                'description' => 'Jalapeno peppers',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Pineapple',
                'value' => 0.90,
                'description' => 'Pineapple',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Sausage',
                'value' => 0.90,
                'description' => 'Sausage',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 13,
                'name' => 'Bacon',
                'value' => 0.90,
                'description' => 'Bacon',
                'is_active' => 'is_active',
            ],
            //medium
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Cheese',
                'value' => 1,
                'description' => 'Cheese',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Tomato sauce',
                'value' => 1,
                'description' => 'Tomato sauce',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Pepperoni',
                'value' => 1,
                'description' => 'Pepperoni',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Ham',
                'value' => 1,
                'description' => 'Ham',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Chicken',
                'value' => 1,
                'description' => 'Chicken',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Minced beef',
                'value' => 1,
                'description' => 'Minced beef',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Onions',
                'value' => 1,
                'description' => 'Onions',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Green peppers',
                'value' => 1,
                'description' => 'Green peppers',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Mushrooms',
                'value' => 1,
                'description' => 'Mushrooms',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Sweetcorn',
                'value' => 1,
                'description' => 'Sweetcorn',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Jalapeno peppers',
                'value' => 1,
                'description' => 'Jalapeno peppers',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Pineapple',
                'value' => 1,
                'description' => 'Pineapple',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Sausage',
                'value' => 1,
                'description' => 'Sausage',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 14,
                'name' => 'Bacon',
                'value' => 1,
                'description' => 'Bacon',
                'is_active' => 'is_active',
            ],
            //large
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Cheese',
                'value' => 1.15,
                'description' => 'Cheese',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Tomato sauce',
                'value' => 1.15,
                'description' => 'Tomato sauce',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Pepperoni',
                'value' => 1.15,
                'description' => 'Pepperoni',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Ham',
                'value' => 1.15,
                'description' => 'Ham',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Chicken',
                'value' => 1.15,
                'description' => 'Chicken',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Minced beef',
                'value' => 1.15,
                'description' => 'Minced beef',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Onions',
                'value' => 1.15,
                'description' => 'Onions',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Green peppers',
                'value' => 1.15,
                'description' => 'Green peppers',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Mushrooms',
                'value' => 1.15,
                'description' => 'Mushrooms',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Sweetcorn',
                'value' => 1.15,
                'description' => 'Sweetcorn',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Jalapeno peppers',
                'value' => 1.15,
                'description' => 'Jalapeno peppers',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Pineapple',
                'value' => 1.15,
                'description' => 'Pineapple',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Sausage',
                'value' => 1.15,
                'description' => 'Sausage',
                'is_active' => 'is_active',
            ],
            [
                'manufacturer_id' => 1,
                'pizza_model_id' => 15,
                'name' => 'Bacon',
                'value' => 1.15,
                'description' => 'Bacon',
                'is_active' => 'is_active',
            ],
        ];

        foreach ($pizza_addons as $pizza_addon) {
            \App\Models\PizzaAddon::create($pizza_addon);
        }
    }
}